CREATE TABLE Countries
(
    ID INT NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Regions
(
    ID INT NOT NULL PRIMARY KEY,
    countryID INT NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    FOREIGN KEY (countryID) 
        REFERENCES Countries(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Locations
(
    ID INT NOT NULL PRIMARY KEY,
    regionID INT NOT NULL,
    locale VARCHAR(100) NOT NULL UNIQUE,
    coordinates VARCHAR(40) NOT NULL UNIQUE,
    FOREIGN KEY (regionID) 
        REFERENCES Regions(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Warehouses
(
    ID INT NOT NULL PRIMARY KEY,
    locationID INT NOT NULL UNIQUE,
    phone VARCHAR(18) NOT NULL UNIQUE,
    FOREIGN KEY (locationID) 
        REFERENCES Locations(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE TypesOfUsers
(
    ID INT NOT NULL PRIMARY KEY,
    type VARCHAR(35) NOT NULL UNIQUE,
    accessLevel INT NOT NULL
);

CREATE TABLE Users
(
    ID INT NOT NULL PRIMARY KEY,
    typeID INT NOT NULL,
    FIO VARCHAR(50) NOT NULL,
    phone VARCHAR(18) NOT NULL UNIQUE,
    dateBirth DATE NOT NULL,
    FOREIGN KEY (typeID)
        REFERENCES TypesOfUsers(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Accounts
(
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    userID INT NOT NULL UNIQUE,
    login VARCHAR(25) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    FOREIGN KEY (userID)
        REFERENCES Users(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Orders
(
    ID INT NOT NULL PRIMARY KEY,
    accountID INT NOT NULL,
    trackNumber VARCHAR(15) NOT NULL UNIQUE,
    totalCost INT NOT NULL,
    completed BOOLEAN NOT NULL,
    FOREIGN KEY (accountID)
        REFERENCES Accounts(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Product
(
    ID INT NOT NULL PRIMARY KEY,
    title VARCHAR(50) UNIQUE NOT NULL,
    cost INT NOT NULL
);

CREATE TABLE ListProducts
(
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    orderID INT NOT NULL,
    productID INT NOT NULL,
    count INT NOT NULL,
    FOREIGN KEY (orderID) 
        REFERENCES Orders(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (productID)
        REFERENCES Products(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE RemnantsOfProducts
(
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    warehouseID INT NOT NULL,
    productID INT NOT NULL,
    count INT NOT NULL,
    FOREIGN KEY (warehouseID)
        REFERENCES Warehouses(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (productID)
        REFERENCES Products(ID)
        ON DELETE CASCADE ON UPDATE NO ACTION
);
